package com.cranajit.business_rule_engine.model;

public enum ActionType {
	GENERATE_PACKING_SLIP,
	GENERATE_AGENT_COMISSION,
	GENERATE_PACKING_SLIP_ROYALTY_DEPERMENT,
	ACTIVATE_MEMBERSHIP,
	UPGRADE_MEMBERSHIP,
	EMAIL_OWNER
}
